# Generated by Django 4.0.4 on 2022-06-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('nom_utilisateur', models.TextField()),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.TextField(default='null', max_length=30, unique=True)),
                ('initial', models.TextField(default='null', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='nom', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('duree', models.TextField(blank=True, max_length=30)),
                ('ingredient', models.ManyToManyField(to='hubby.ingredient')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubby.origine')),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('position', models.IntegerField(unique=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubby.recette')),
            ],
        ),
    ]
