# Generated by Django 4.0.4 on 2022-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='position',
            field=models.IntegerField(),
        ),
    ]
