# Generated by Django 4.0.4 on 2022-09-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubby', '0002_alter_etape_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, max_length=255)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubby.recette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubby.user')),
            ],
        ),
    ]
